version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - boomtable-dependencies-{{ checksum "package.json" }}
          - boomtable-dependencies-
      - run: 
          name : Build
          command : |
            npm install
            npm run build
      - save_cache:
          paths:
            - node_modules
          key: boomtable-dependencies-{{ checksum "package.json" }}
