name: Test & Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install
      run: |
        echo "Grafana Boom Table plugin - Install dependencies";
        yarn install --frozen-lockfile;
    - name: Test
      run: |
        echo "Grafana Boom Table plugin - Test";
        yarn test;
    - name: Build
      run: |
        echo "Grafana Boom Table plugin - Build";
        yarn build;